apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: {{ include "deployment_fullname" }}
spec:
    minReplicas: 1
    maxReplicas: 10
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: {{ include "deployment_fullname" }}
    metrics:
        - type: Resource
            resource:
                name: cpu
                target:
                    type: Utilization
                    averageValue: 50m
    behavior:
        scaleDown:
            stabilizationWindowSeconds: 180
            policies:
                - type: Exponential
                  value: 2
                  periodSeconds: 60
        scaleUp:
            stabilizationWindowSeconds: 180
            policies:
                - type: Exponential
                  value: 2
                  periodSeconds: 60
