apiVersion: v1
kind: Service
metadata:
    name: {{ include "service_fullname" }}
spec:
    type: LoadBalancer
    selector:
        app: {{ include "deployment_fullname" }}
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
    clusterIP: None
